default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_group_development

test:
  <<: *default
  database: recipe_group_test

production:
  <<: *default
  database: recipe_group_production
  username: recipe_group
  password: <%= ENV["RECIPE_GROUP_DATABASE_PASSWORD"] %>
